"""Worked output: Phase 1 baseline report.

Reads the saved fixtures, runs the load primitives end-to-end, and writes a
markdown report into runs/. Re-runnable. Useful both for sanity-checking
the methodology and as a template for the weekly_review orchestrator (Phase 5).
"""
from __future__ import annotations

import json
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from primitives.load import (
    BUILD_TABLE,
    atl_ctl_gap_streak,
    banister_series,
    daily_tss,
    dedupe_activities,
    fitness_rows_to_loadpoints,
    flag_conditions,
    separate_actual_projection,
    trajectory_check,
    weekly_ramp,
)

FIXTURES = ROOT / "fixtures"
RUNS = ROOT / "runs"
RUNS.mkdir(exist_ok=True)


def fmt_date(d: date) -> str:
    return d.strftime("%a %d %b")


def main() -> Path:
    today = date(2026, 4, 25)

    # --- Load data --------------------------------------------------------
    fitness = json.loads(
        (FIXTURES / "fitness_2026_01_25_to_2026_04_25.json").read_text()
    )["rows"]
    activities_raw = json.loads(
        (FIXTURES / "activities_2026_03_27_to_2026_04_25.json").read_text()
    )["activities"]

    # --- Dedup + daily TSS ----------------------------------------------
    raw_count = len(activities_raw)
    deduped = dedupe_activities(activities_raw)
    deduped_count = len(deduped)
    dropped = raw_count - deduped_count

    # Identify the dropped duplicates by id for transparency
    raw_ids = {a["id"] for a in activities_raw}
    kept_ids = {a["id"] for a in deduped}
    dropped_ids = raw_ids - kept_ids

    daily = daily_tss(activities_raw)

    # Daily TSS totals also computed without dedup, for the transparency block
    raw_daily: dict[date, float] = {}
    for a in activities_raw:
        ts = a.get("date")
        tss = a.get("tss")
        if ts is None or tss is None:
            continue
        d = datetime.fromisoformat(ts).date()
        raw_daily[d] = raw_daily.get(d, 0.0) + float(tss)

    # --- Independent Banister recomputation ----------------------------
    # Seed from the API fitness row 30 days before today.
    seed_row = next(r for r in fitness if r["date"] == "2026-03-27")
    seed_ctl, seed_atl = float(seed_row["ctl"]), float(seed_row["atl"])

    recompute_start = date(2026, 3, 28)  # day after seed
    recompute_end = today + timedelta(days=14)  # project two weeks ahead
    recomputed = banister_series(
        daily, recompute_start, recompute_end,
        seed_ctl=seed_ctl, seed_atl=seed_atl,
        today=today,
    )

    # --- API-side LoadPoints for cross-check ---------------------------
    api_points = fitness_rows_to_loadpoints(fitness, today=today, daily=daily)

    # --- Derived metrics ------------------------------------------------
    ramps = weekly_ramp(api_points)
    gap_streak = atl_ctl_gap_streak(api_points)
    flags = flag_conditions(api_points, ankle_in_rehab=True, today=today)
    trajectory = trajectory_check(api_points)
    actual, projection = separate_actual_projection(recomputed, today)

    # --- Pair API vs recomputed for cross-check --------------------------
    by_api_date = {p.date: p for p in api_points}
    cross_check_rows = []
    for r in recomputed:
        if r.is_projection:
            continue
        api = by_api_date.get(r.date)
        if not api:
            continue
        cross_check_rows.append((r.date, api.ctl, r.ctl, api.atl, r.atl, api.tsb, r.tsb))

    # Aggregate cross-check error
    if cross_check_rows:
        max_ctl_err = max(abs(api - rec) for _, api, rec, *_ in cross_check_rows)
        max_atl_err = max(abs(api - rec) for _, _, _, api, rec, _, _ in cross_check_rows)
    else:
        max_ctl_err = max_atl_err = 0.0

    # --- Render -----------------------------------------------------------
    out: list[str] = []
    out.append(f"# Load baseline — worked output ({today.isoformat()})")
    out.append("")
    out.append("Generated by `scripts/run_baseline.py` from `primitives/load.py`. "
               "This is the Phase 1 sanity-check report. Methodology must be "
               "validated against this output before Phase 2 (volume + heat).")
    out.append("")
    out.append("## Today")
    out.append("")
    api_today = by_api_date[today]
    out.append(f"- **CTL** {api_today.ctl:.1f}  (Intervals.icu)")
    out.append(f"- **ATL** {api_today.atl:.1f}")
    out.append(f"- **TSB** {api_today.tsb:+.1f}  ({api_today.tsb_pct:+.1f}%)")
    out.append(f"- ATL−CTL gap: {api_today.atl - api_today.ctl:+.1f}")
    out.append("")

    # Active flags
    out.append("## Flags")
    out.append("")
    if not flags:
        out.append("_No flags triggered._")
    else:
        for f in flags:
            out.append(f"- **[{f.severity.upper()}] {f.code}** ({f.triggered_on.isoformat()}): {f.message}")
    out.append("")

    # Gap streak detail
    out.append("## ATL−CTL gap streak")
    out.append("")
    out.append(f"- In breach today (gap > 25): **{gap_streak['in_breach_today']}**")
    out.append(f"- Current consecutive-days streak: **{gap_streak['current_streak_days']}**")
    out.append(f"- Longest streak in window: **{gap_streak['longest_streak_days']}**"
               f"{' (ended ' + gap_streak['longest_streak_ended'].isoformat() + ')' if gap_streak['longest_streak_ended'] else ''}")
    out.append("")

    # Trajectory check
    out.append("## Trajectory vs build-table targets")
    out.append("")
    out.append("| Milestone | Target date | Target CTL | Projected/actual | Δ low | Status |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for t in trajectory:
        proj_marker = "*" if t["is_projected"] else ""
        out.append(
            f"| {t['label']} | {t['target_date'].isoformat()} | "
            f"{t['target_ctl_low']:.0f}–{t['target_ctl_high']:.0f} | "
            f"{t['ctl_on_target_date']:.1f}{proj_marker} | "
            f"{t['delta_low']:+.1f} | **{t['status']}** |"
        )
    out.append("")
    out.append("`*` projected from current 14-day average ramp. Naive — does not "
               "model the planned build (Phase 5 orchestrator will).")
    out.append("")

    # Recent ramps
    out.append("## Recent weekly ramp (7-day ΔCTL)")
    out.append("")
    out.append("| Date | ΔCTL/wk |")
    out.append("| --- | --- |")
    for d, r in ramps[-14:]:
        out.append(f"| {d.isoformat()} | {r:+.1f} |")
    out.append("")

    # Cross-check
    out.append("## Cross-check: my Banister vs Intervals.icu")
    out.append("")
    out.append(f"Re-seeded from {recompute_start - timedelta(days=1)} CTL/ATL "
               f"({seed_ctl:.1f}/{seed_atl:.1f}); recomputed 28 days using my "
               f"daily-TSS series (with dedup) vs the API's stored values.")
    out.append("")
    out.append(f"- Max CTL error: **{max_ctl_err:.2f}**")
    out.append(f"- Max ATL error: **{max_atl_err:.2f}**")
    out.append("")
    out.append("If errors > ~2.0, suspect a methodology mismatch (Intervals may "
               "use 12-day TSS warm-up, slightly different decay implementation, "
               "or include manual TSS entries not visible to MCP). The 14 April "
               "double-count means Intervals' CTL is *slightly inflated* on days "
               "after the duplicate; my series should track lower.")
    out.append("")
    out.append("| Date | API CTL | Mine | API ATL | Mine | API TSB | Mine |")
    out.append("| --- | --- | --- | --- | --- | --- | --- |")
    # Show the last 14 days of the cross-check
    for d_, api_c, my_c, api_a, my_a, api_t, my_t in cross_check_rows[-14:]:
        out.append(f"| {d_.isoformat()} | {api_c:.1f} | {my_c:.1f} | "
                   f"{api_a:.1f} | {my_a:.1f} | {api_t:+.1f} | {my_t:+.1f} |")
    out.append("")

    # Dedup transparency
    out.append("## Activity dedup")
    out.append("")
    out.append(f"- Raw activity count (last 30 days): **{raw_count}**")
    out.append(f"- After dedup: **{deduped_count}**")
    out.append(f"- Dropped: **{dropped}** ({sorted(dropped_ids)})")
    out.append("")
    if date(2026, 4, 14) in raw_daily:
        out.append(f"- 14 April raw daily TSS: **{raw_daily[date(2026, 4, 14)]:.0f}**")
        out.append(f"- 14 April deduped daily TSS: **{daily.get(date(2026, 4, 14), 0):.0f}**")
        out.append(f"- Difference: **{raw_daily[date(2026, 4, 14)] - daily.get(date(2026, 4, 14), 0):.0f}** TSS — Intervals' stored CTL/ATL include the duplicate.")
    out.append("")

    # Daily TSS series (last 14 days)
    out.append("## Daily TSS — last 14 days (deduplicated)")
    out.append("")
    out.append("| Date | TSS |")
    out.append("| --- | --- |")
    for offset in range(13, -1, -1):
        d_ = today - timedelta(days=offset)
        out.append(f"| {d_.isoformat()} ({fmt_date(d_)}) | {daily.get(d_, 0):.0f} |")
    out.append("")

    # Projection
    out.append("## 14-day forward projection (zero-training)")
    out.append("")
    out.append("This is what happens if you do nothing from tomorrow onward. "
               "Useful as a floor for taper planning — *not* a training plan.")
    out.append("")
    out.append("| Date | CTL | ATL | TSB | TSB% |")
    out.append("| --- | --- | --- | --- | --- |")
    for p in projection:
        out.append(f"| {p.date.isoformat()} | {p.ctl:.1f} | {p.atl:.1f} | "
                   f"{p.tsb:+.1f} | {p.tsb_pct:+.1f}% |")
    out.append("")

    # Athlete profile snapshot for context
    out.append("## Athlete context (read at session start)")
    out.append("")
    out.append("- Athlete `i196362` (Jamie Diamond), Europe/London tz")
    out.append("- Ride FTP **316 W** (Intervals authoritative; project doc said 320 — superseded)")
    out.append("- Ankle in rehab — ramp-flag threshold tightened to +4 CTL/wk")
    out.append("- Subjective wellness ignored by design (athlete decision)")
    out.append("")

    out.append("---")
    out.append("")
    out.append("Data provided by Garmin®")
    out.append("")

    report_path = RUNS / f"{today.isoformat()}-load-baseline.md"
    report_path.write_text("\n".join(out))
    print(f"wrote {report_path}")
    print(f"max ctl/atl cross-check error: {max_ctl_err:.2f} / {max_atl_err:.2f}")
    return report_path


if __name__ == "__main__":
    main()
